zh:
  label: 中文
  locale: zh-CN
  contentDir: content/zh
  weight: 1
  title: 连慧婕 | Huijie Lian
  menus:
    main:
      - name: 首页
        pageRef: /
        weight: 10
      - name: 论文
        pageRef: /publications
        weight: 20
      - name: 关于我
        pageRef: /about
        weight: 30
en:
  label: English
  locale: en-US
  contentDir: content/en
  weight: 2
  title: Huijie Lian
  menus:
    main:
      - name: Home
        pageRef: /
        weight: 10
      - name: Publications
        pageRef: /publications
        weight: 20
      - name: About
        pageRef: /about
        weight: 30
